// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TheSimpsons;
//
//    var personaje = Personaje.FromJson(jsonString);

namespace TheSimpsons
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Personaje
    {
        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("age")]
        public long? Age { get; set; }

        [JsonProperty("birthdate")]
        public DateTimeOffset? Birthdate { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("first_appearance_ep_id")]
        public long? FirstAppearanceEpId { get; set; }

        [JsonProperty("first_appearance_sh_id")]
        public long? FirstAppearanceShId { get; set; }

        [JsonProperty("gender")]
        public string? Gender { get; set; }

        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("occupation")]
        public string? Occupation { get; set; }

        [JsonProperty("phrases")]
        public List<string>? Phrases { get; set; }

        [JsonProperty("portrait_path")]
        public string? PortraitPath { get; set; }

        [JsonProperty("status")]
        public string? Status { get; set; }

        [JsonProperty("first_appearance_ep")]
        public FirstAppearance? FirstAppearanceEp { get; set; }

        [JsonProperty("first_appearance_sh")]
        public FirstAppearance? FirstAppearanceSh { get; set; }
    }

    public partial class FirstAppearance
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("airdate")]
        public DateTimeOffset? Airdate { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("episode_number")]
        public long EpisodeNumber { get; set; }

        [JsonProperty("image_path")]
        public string ImagePath { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("season")]
        public long Season { get; set; }

        [JsonProperty("synopsis")]
        public string Synopsis { get; set; }
    }

    public partial class Personaje
    {
        public static Personaje FromJson(string json) => JsonConvert.DeserializeObject<Personaje>(json, TheSimpsons.Converter.Settings);
    }

    public static class SerializePersonaje
    {
        public static string ToJson(this Personaje self) => JsonConvert.SerializeObject(self, TheSimpsons.Converter.Settings);
    }

    internal static class ConverterPersonaje
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            NullValueHandling = NullValueHandling.Ignore,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
